**Numpy creating arrays chapter 1**

*version, np.arange, reshape, empty, eye, identity, ones, zeros, ones_like, zeros_like, full, full_like, hstack, vstack, concatenate*




In [13]:
import numpy as np
print(np.__version__)

1.21.6


In [2]:
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [7]:
a=np.arange(0,100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
a=np.arange(0,100).reshape(5,20)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [12]:
a=np.arange(1,10,dtype='float')
print(a)
print(a.dtype)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [14]:
a=np.arange(0,100,2,dtype='int8')
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [17]:
a=np.empty((2,3),dtype='int32')
print(a)

[[         0 1072168960          0]
 [1072168960          0          0]]


In [19]:
b=np.empty_like(a,dtype='float64')
print(b)

[[3.2033691e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [24]:
onediagonal=np.eye(3,4)
print(onediagonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [25]:
onediagonal=np.eye(4,5,k=2)
print(onediagonal)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [26]:
identity=np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
ones=np.ones((2,3))
print(ones)

[[ True  True  True]
 [ True  True  True]]


In [31]:
truth=np.ones(ones.shape,dtype='bool')
print(truth)

[[ True  True  True]
 [ True  True  True]]


In [33]:
zero=np.zeros(truth.shape,dtype='int32')
print(zero)

[[0 0 0]
 [0 0 0]]


In [34]:
false=np.zeros(zero.shape,dtype='bool')
print(false)

[[False False False]
 [False False False]]


In [35]:
zeros=np.zeros_like(zero,dtype='int64')
print(zeros)

[[0 0 0]
 [0 0 0]]


In [36]:
fill=np.full_like(zeros,4,dtype='int32')
print(fill)

[[4 4 4]
 [4 4 4]]


In [43]:
fill=np.full((4,5),np.random.randint(10,100),dtype='int32')
print(fill)

[[31 31 31 31 31]
 [31 31 31 31 31]
 [31 31 31 31 31]
 [31 31 31 31 31]]


In [46]:
fill=np.full((100,),4)
print(fill)


[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]


In [48]:
fill=fill.reshape(10,10)
print(fill)

[[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]


In [57]:
fill[:,-2:-1]=8
print(fill)

[[4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]
 [4 4 4 4 4 4 4 4 8 4]]


In [66]:
fill[:,-1:]=9
print(fill)


[[0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]
 [0 4 4 4 4 4 4 4 8 9]]


In [67]:
fill[:,0:1]-=4
print(fill)

[[-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]
 [-4  4  4  4  4  4  4  4  8  9]]


In [101]:
zero=np.zeros((5),dtype='int32')
print(zero)
print("size",zero.size,len(zero)," shape:", zero.shape)
zero=np.concatenate((zero,np.array([3])))
zero=zero.reshape(2,3)
print(zero)

[0 0 0 0 0]
size 5 5  shape: (5,)
[[0 0 0]
 [0 0 3]]


In [103]:
n=np.ones((2,3),dtype='int32')
n=np.hstack((zero,n))
print(n)

[[0 0 0 1 1 1]
 [0 0 3 1 1 1]]


In [105]:
n=np.vstack((n,n))
print(n)

[[0 0 0 1 1 1]
 [0 0 3 1 1 1]
 [0 0 0 1 1 1]
 [0 0 3 1 1 1]]


In [108]:
n=np.ones((2,3),dtype='int32')
n=np.concatenate((zero,n),axis=1)
print(n)

[[0 0 0 1 1 1]
 [0 0 3 1 1 1]]


In [110]:
n=np.concatenate((n,n),axis=0)
print(n)

[[0 0 0 1 1 1]
 [0 0 3 1 1 1]
 [0 0 0 1 1 1]
 [0 0 3 1 1 1]]
